---
namespace: k0s
name: platform
version: 1.0.0
readme: README.md
authors:
  - smoothzz
description: >-
  Install and manage multi-node k0s Kubernetes clusters with selectable
  topologies (single, CPLB HA, single external LB, multi external LB HA)
  and selectable CNI (kuberouter, calico, cilium).
license:
  - MIT
tags:
  - kubernetes
  - k0s
  - cluster
  - highavailability
  - etcd
  - infrastructure
  - linux
dependencies: {}
repository: https://github.com/smoothzz/k0s-platform
documentation: https://github.com/smoothzz/k0s-platform
issues: https://github.com/smoothzz/k0s-platform/issues
build_ignore:
  - "*.tar.gz"
